spring.application.name=burntz

spring.profiles.active=dev

# ---- JWT ?? ----
jwt.secret=${JWT_SECRET}

# 1?? (ms)
jwt.accessTokenExpirationTime=3600000
# 7? (ms)
jwt.refreshTokenExpirationTime=604800000

logging.level.com.fitian.burntz=DEBUG