spring.config.activate.on-profile=dev

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.default_schema=burntz



# ---- OAuth2 (Google, Apple) ----

# Google
spring.security.oauth2.client.registration.google.client-id=${BURNTZ_DEV_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${BURNTZ_DEV_GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

## Apple OAuth2 (replace placeholders)
#spring.security.oauth2.client.registration.apple.client-id=BURNTZ_APPLE_SERVICE_ID
#spring.security.oauth2.client.registration.apple.client-secret=BURNTZ_GENERATED_JWT_HERE
#spring.security.oauth2.client.registration.apple.client-authentication-method=client_secret_post
#spring.security.oauth2.client.registration.apple.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.apple.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
#spring.security.oauth2.client.registration.apple.scope=openid,email
#
#spring.security.oauth2.client.provider.apple.authorization-uri=https://appleid.apple.com/auth/authorize
#spring.security.oauth2.client.provider.apple.token-uri=https://appleid.apple.com/auth/token
