spring.application.name=burntz

spring.profiles.active=dev

# ---- JWT ?? ----
jwt.base64-secretKey=${JWT_BASE64_SECRET}

# 1?? (ms)
jwt.accessTokenExpirationTime=3600000
# 7? (ms)
jwt.refreshTokenExpirationTime=604800000