spring.application.name=burntz

spring.profiles.active=dev

# ---- JWT ?? ----
jwt.secret=${JWT_SECRET}

# 1?? (ms)
jwt.accessTokenExpirationTime=3600000
# 7? (ms)
jwt.refreshTokenExpirationTime=604800000


# RestTemplate / HTTP client ?? (ms ??)
app.http.connect-timeout-ms=5000
app.http.socket-timeout-ms=10000
app.http.connection-request-timeout-ms=3000

# connection pool setting
app.http.max-total-connections=200
app.http.max-per-route=50
app.http.evict-idle-seconds=30

pring.autoconfigure.exclude=org.springframework.boot.autoconfigure.http.client.HttpClientAutoConfiguration,\
  org.springframework.boot.autoconfigure.web.client.RestClientAutoConfiguration

# Timezone Setting(UTC)
spring.jpa.properties.hibernate.jdbc.time_zone : UTC

# retry setting option (defaults are shown in the handler constructor annotations)
retry.maxAttempts=3
retry.baseBackoffMillis=200
retry.maxBackoffMillis=2000