#AWS REDIS
#spring.data.redis.host=${REDIS_HOST}
#spring.data.redis.port=${REDIS_PORT}
#spring.data.redis.password=${REDIS_AUTH_TOKEN}
#spring.data.redis.ssl.enabled=true
#management.endpoint.health.show-details= always